# Generated by Django 3.1.1 on 2020-09-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(verbose_name='Дата')),
                ('invite_reason', models.CharField(max_length=64, verbose_name='Причина приглашения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Группа')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Музыкант')),
            ],
            options={
                'verbose_name': 'Текущий состав',
                'verbose_name_plural': 'Текущие составы',
                'ordering': ['group', 'date_joined'],
            },
        ),
    ]
